version: '3.7'

services:     
  mariadb:
    container_name: sportsof-mariadb
    hostname: mariadb
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: webdb
      MARIADB_USER: webdb
      MARIADB_PASSWORD: password
    ports:
      - "0.0.0.0:5023:3306"
    networks:
      - kafkanet
      
  web:
    container_name: sportsof-web-app
    hostname: api
    build: MyWebApplication/
    ports:
      - "0.0.0.0:5003:5003"
      
networks:
  kafkanet:
    name: kafkanet
    external: true